version: 2

models:
  - name: active_users
    description: "사용자 별 이벤트 수를 계산한 모델"
    columns:
      - name: user_id
        description: "사용자 ID"
        tests:
          - not_null
          - unique

      - name: event_count
        description: "사용자의 전체 이벤트 수"
        tests:
          - not_null
